name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run script
      run: echo Hello, world
    - name: run 2 script
      run: |
        echo Hello, world2
        echo Hello, world3
